import { displayName, getObjectives, type Entity } from "./entity.ts";
import { assertAgentId } from "./ops.ts";
import type { Vault } from "./vault.ts";
import { link, unwrapLink } from "./wikilink.ts";

export const HANDBOOK_PATH = "HANDBOOK.md";

function questLine(q: Entity): string {
  const objectives = getObjectives(q);
  const done = objectives.filter((o) => o.done).length;
  const owner = q.fm.owner ? ` · owner ${link(unwrapLink(q.fm.owner))}` : "";
  const progress = objectives.length ? ` · ${done}/${objectives.length} objectives` : "";
  const deadline = q.fm.deadline ? ` · due ${q.fm.deadline}` : "";
  return `- ${link(q.slug)} — ${q.fm.status ?? "active"}${owner}${progress}${deadline}`;
}

export function activeQuests(vault: Vault): Entity[] {
  return vault.ofType("quest").filter((q) => !["done", "failed"].includes(q.fm.status ?? "active"));
}

/** The Player's Handbook: everything an agent needs to read and write this vault correctly. */
export function renderHandbook(vault: Vault): string {
  const { config } = vault;
  const inbox = config.folders.inbox;
  const party = vault.ofType("party");
  const types = Object.entries(config.types)
    .map(([name, def]) => `| \`${name}\` | \`${def.folder}/\` | ${def.description} |`)
    .join("\n");
  const partyRows = party
    .map((p) => `| \`${p.slug}\` | ${displayName(p)} | ${p.fm.lane ?? ""} | ${(p.fm.authority ?? []).join(", ")} |`)
    .join("\n");
  const quests = activeQuests(vault).map((q) => questLine(q)).join("\n") || "- (none)";
  const disputes = vault.openDisputes().map((d) => `- ${link(d.slug)} — ${d.fm.entity} · ${d.fm.field}`).join("\n") || "- (none)";

  return `---
type: handbook
generated: true
---
# 📜 Player's Handbook — ${config.campaign}

> [!warning] Generated by Hippocampus. Do not edit.
> Change \`_hippo/config.yaml\` or \`party/*.md\` instead. This file is regenerated on every sleep.

This vault is the party's **shared memory**, organized like a TTRPG campaign wiki. It holds characters, factions, locations, items, lore, quests, and a chronicle of what happened.
**Hippocampus** is the curator. Agents never edit canon notes. You submit *episodes* (raw memories) with the \`remember\` tool, and they wait in the inbox. Every night Hippocampus **sleeps**: it consolidates episodes into canon, links entities, and resolves conflicts. Contradictions it can't settle become disputes for ${link(config.human)} to rule on.

## ✍️ How to remember something

Use the Hippocampus MCP tools, and don't edit files in this vault yourself: the tools run the checks that keep this memory trustworthy.

Call **\`remember\`** once per memory:

- \`text\` (required): the memory in plain language, self-contained, at most 8 KB.
- \`kind\`: \`observation\` (default) | \`fact\` | \`decision\` | \`task\` | \`beat\` | \`question\`
- \`about\`: optional hints, as links or names, e.g. \`["[[residence-permit]]", "Agência de Migração"]\`
- \`secret: true\` if it contains IDs, account numbers or credentials. They get encrypted.
- \`confidence\` (0–1) and \`at\` (ISO 8601, when it happened; defaults to now).
- \`agent\`: your agent id (see Party below), unless your connection is already bound to one.

Writing tips, so the curator gets it right:
- One memory per call. Short, concrete, self-contained. Name people, places, and orgs explicitly.
- Exact values: ISO dates (\`2026-10-14\`), amounts with currency (\`4,500 TRY\`), full IDs, emails, and phone numbers.
- Say *how you know* ("confirmed by email from …", "seen on the permit portal") when it matters.
- Corrections are just new memories ("appointment moved to …"). Don't try to change old ones.
- Quest progress: \`update_quest\` records objectives, clocks and status directly. Story beats for the game master: \`kind: beat\`.

## 👋 Introduce yourself

If \`onboard\` says you aren't in the party, call **\`introduce\`** once: your agent id, a display \`title\`, your \`lane\` (what you handle, in a sentence), and optionally \`host\`, \`model\` and \`about\`. ${link(config.human)} approves you and decides your authority. Until then your memories are accepted, but they count as rumors. Introducing yourself again replaces your earlier introduction.

### Inbox file format (for local tools that write files)

A tool that can't use MCP writes **one new file per memory** to \`${inbox}/<agent-id>/<YYYY-MM-DDTHHMMSS>-<short-slug>.md\` and never modifies or deletes other files:

\`\`\`markdown
---
agent: residency-agent          # your agent id
kind: fact               # observation | fact | decision | task | beat | question
at: 2026-09-27T14:03:00+01:00
about: ["[[residence-permit]]", "Agência de Migração"]   # optional hints: links or names
secret: false            # true if it contains IDs/numbers that must be encrypted
---
The Agência de Migração appointment moved to 2026-10-14 10:30 at the Alfama office.
Bring: passport, 2 biometric photos, signed rental contract.
\`\`\`

## 📖 How to read memory

- Over MCP: \`recall\` searches, \`get\` returns one entity in full, \`neighbors\` walks relations, \`ask_canon\` answers exact-value questions, and \`briefing\` says what changed lately.
- In the files: each entity has a note in its folder (table below). Obsidian resolves \`[[links]]\` by file name or alias.
- **Facts** are in each note's frontmatter under \`facts:\`, with a status:
  - \`canon\` — accepted truth. Rely on it.
  - \`rumor\` — reported once by a non-authoritative source. Verify before acting.
  - \`disputed\` — sources disagree. See \`${config.folders.disputes}/\`. Don't act on it without checking.
- \`🔒 secret\` values are encrypted in \`${config.folders.secrets}/\`. Ask ${link(config.human)} if you need one.
- **Relations** are under \`relations:\` (\`rel\` + \`target\`).
- **Quest objectives** are the checklist in the quest note.
- \`${config.folders.chronicle}/YYYY/MM/YYYY-MM-DD.md\` is the day-by-day log of consolidated episodes. Facts cite them via \`src\`.
- \`${inbox}/\` holds memories not yet consolidated. They are useful for very recent context but unverified.

## 🧭 Entity types

| type | folder | what goes there |
| --- | --- | --- |
${types}

Relations vocabulary: ${config.relations.map((r) => `\`${r}\``).join(", ")}
Domains (tags that define lanes): ${config.domains.map((d) => `\`${d}\``).join(", ") || "(none)"}

## 🛡 Party

Stay in your lane. Your word is **authoritative** (becomes canon immediately) only for entities tagged with your authority domains. Elsewhere it is a rumor until corroborated.

| id | name | lane | authority |
| --- | --- | --- | --- |
${partyRows}

## 🗺 Active quests

${quests}

## ⚖ Open disputes

${disputes}
`;
}

const titleOf = (id: string) => id.replace(/-+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

/** Who `agent` is to this vault: a party member, waiting for approval, unknown, or not a valid id. */
function whoAmI(vault: Vault, agent: string): string {
  const human = vault.config.human;
  let id: string;
  try {
    id = assertAgentId(vault, agent);
  } catch (err) {
    return `# \`${agent}\` can't be your agent id

${(err as Error).message}. Pick your own id (lowercase letters, digits and dashes, e.g. \`residency-agent\`) and pass it as \`agent\`.
`;
  }
  const me = vault.partyMember(id);
  if (me) {
    const mine = activeQuests(vault).filter((q) => q.fm.owner && unwrapLink(q.fm.owner) === me.slug);
    return `# You are ${displayName(me)} (\`${me.slug}\`)

**Lane:** ${me.fm.lane ?? "(unspecified)"}
**Authority domains:** ${(me.fm.authority ?? []).join(", ") || "(none, so your facts start as rumors)"}

**Your quests:**
${mine.map((q) => questLine(q)).join("\n") || "- (none)"}
`;
  }
  const intro = vault.introductionOf(id);
  if (intro) {
    return `# Introduced as ${intro.title} (\`${id}\`)

Your introduction is waiting for ${human}'s approval (filed ${intro.at.slice(0, 10)}). Until then your memories are accepted, but they count as rumors. Calling \`introduce\` again replaces it.
`;
  }
  return `# Unknown agent \`${id}\`

You are not in the party yet. Your memories are accepted, but they count as rumors until ${human} approves you. Introduce yourself once:

\`\`\`
introduce({ agent: "${id}", title: "${titleOf(id)}", lane: "what you handle, in one sentence", host: "where you run, e.g. Claude Desktop", model: "your model", about: "what you do, in a few lines" })
\`\`\`
`;
}

/** Handbook plus a personal briefing for one agent (the MCP \`onboard\` tool). */
export function renderOnboarding(vault: Vault, agent: string): string {
  const toolsNote = `
Use the MCP tools, and don't edit vault files yourself: \`remember\` files a memory, \`recall\` / \`get\` / \`ask_canon\` read memory, and \`update_quest\` records quest progress.
`;
  return `${whoAmI(vault, agent)}${toolsNote}\n---\n\n${renderHandbook(vault).replace(/^---[\s\S]*?---\n/, "")}`;
}
